version: 0.2

phases:
  install:
    commands:
      - echo installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
    pre_build:
      commands:
        - echo installing dependencies
        - npm install
    
    build:
      commands:
        - echo building...
        - npm run-script build
    post_build:
      commands:
        - ls
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist